# Generated by Django 3.2 on 2022-12-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clothescolor_clothesinstock_clothessize'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSSubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Подписка на RSS',
                'verbose_name_plural': 'Подписки на RSS',
            },
        ),
    ]
